/*
 * KlondilePlainTextSerializerDeserializerConstants.h
 *
 *  Created on: 10 Nov 2016
 *      Author: dancre
 */

#ifndef SRC_SERIALIZERS_DESERIALIZERS_PLAIN_TEXT_INC_KLONDILEPLAINTEXTSERIALIZERDESERIALIZERCONSTANTS_H_
#define SRC_SERIALIZERS_DESERIALIZERS_PLAIN_TEXT_INC_KLONDILEPLAINTEXTSERIALIZERDESERIALIZERCONSTANTS_H_

#include <string>

namespace KlondikePlainTextSerializerDeserializer {
const std::string DECKTYPE_END_MARK = "END_OF_DECKTYPE";
const std::string SCORE_END_MARK = "END_OF_SCORE";
const std::string STOCK_END_MARK = "END_OF_STOCK";
const std::string WASTE_END_MARK = "END_OF_WASTE";
const std::string FOUNDATION_END_MARK = "END_OF_FOUNDATION";
const std::string FOUNDATIONS_END_MARK = "END_OF_FOUNDATIONS";
const std::string TABLEAU_PILE_COVERED_END_MARK = "END_OF_TABLEAU_PILE_COVERED";
const std::string TABLEAU_PILE_END_MARK = "END_OF_TABLEAU_PILE";
const std::string TABLEAU_END_MARK = "END_OF_TABLEAU";
}

#endif /* SRC_SERIALIZERS_DESERIALIZERS_PLAIN_TEXT_INC_KLONDILEPLAINTEXTSERIALIZERDESERIALIZERCONSTANTS_H_ */
